Fix sed regex replacing IPv6 listening address
haugene/docker-transmission-openvpn pull request #2673
Opened 2023-07-31 07:32 UTC by mathiasflorin

The regular expression .* replaces the listening address on both of the following lines in the default config:

```
listen-address  127.0.0.1:8118
listen-address  [::1]:8118

```
The next sed expression to remove ipv6 will not match anymore. Privoxy will also try to bind twice to the same address and is not working with this invalid configuration.

## Breaking change

```txt
<placeholder>
```

## Proposed change

```txt
<placeholder>
```

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this container)
- [ ] Breaking change (fix/feature causing existing functionality to break)

## Additional information

- This PR fixes or closes issue: ```fixes #```
- This PR is related to issue: ```relates to #```
- Link to documentation updated (if done separately): ```https://...```

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated

2023-08-05 16:41 UTC, JeeDeWee commented
I am not an sed expert but there must be a problem with the syntax. After a few restarts the config file is now:

```
172.20.0.3:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118:8118
```

2023-08-06 14:04 UTC, mathiasflorin commented
Hi @JeeDeWee , I forgot to replace the port. Sorry for the inconvenience caused.

Can you please try again with the commit I added now?

2023-08-07 13:09 UTC, JeeDeWee requested changes
/I have modified line 30 in your code to read:

`sed -i -E "s/^listen-address.*/listen-address ${adr}:$1/" "$2"`

To avoid conflicts with the IPV6 addresses I moved lines 32 and 33 after row 25. This way, any IPV6 reference will get deleted and you will only have an IPV4 address.

2023-08-07 13:18 UTC, mathiasflorin commented
Thank you @JeeDeWee.

Will you push your changes directly to the dev branch so that I can close my pull request?

2023-08-07 13:20 UTC, mathiasflorin commented
Thank you @JeeDeWee

2023-08-07 13:50 UTC, JeeDeWee commented
Will do. I have created a pull request #2678

Op ma 7 aug 2023 om 15:19 schreef Mathias Florin ***@***.***>:

> Thank you @JeeDeWee <https://github.com/JeeDeWee>.
>
> Will you push your changes directly to the dev branch so that I can close
> my pull request?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/haugene/docker-transmission-openvpn/pull/2673#issuecomment-1667844599>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANUHCI6HQXWTAUPLXF4Q7YLXUDTMPANCNFSM6AAAAAA252Y6ZM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-07 13:58 UTC, mathiasflorin commented
I am closing this pull request as @JeeDeWee approach is also valid.

2023-08-07 13:58 UTC, mathiasflorin commented
I am closing this pull request as @JeeDeWee approach is also valid.

2023-08-07 13:58 UTC, closed without merging